# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contract', models.CharField(max_length=20)),
                ('number_contract', models.IntegerField()),
                ('period_summer', models.CharField(choices=[('ene_jun', 'Enero - Junio'), ('jun_dic', 'Junio - Diciembre')], max_length=20)),
                ('type_payment', models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('tarifa1', 'TARIFA 1'), ('tarifa1a', 'TARIFA 1A'), ('tarifa1b', 'TARIFA 1B'), ('tarifa1c', 'TARIFA 1C'), ('tarifa1d', 'TARIFA 1D'), ('tarifa1e', 'TARIFA 1E'), ('tarifa1f', 'TARIFA 1F')], max_length=20)),
                ('key_mun', models.IntegerField()),
                ('name_mun', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('key_state__key_state',),
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rate', models.CharField(choices=[('tarifa1', 'TARIFA 1'), ('tarifa1a', 'TARIFA 1A'), ('tarifa1b', 'TARIFA 1B'), ('tarifa1c', 'TARIFA 1C'), ('tarifa1d', 'TARIFA 1D'), ('tarifa1e', 'TARIFA 1E'), ('tarifa1f', 'TARIFA 1F')], max_length=15)),
                ('period_name', models.CharField(choices=[('verano', 'Verano'), ('noverano', 'Fuera de Verano')], max_length=20)),
                ('consumption_name', models.CharField(choices=[('consumobasico', 'Consumo Básico'), ('consumointermedio', 'Consumo Intermedio'), ('consumointermedioalto', 'Consumo Intermedio Alto'), ('consumoexcedente', 'Consumo Excedente')], max_length=20)),
                ('kilowatt', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payday_limit', models.DateField()),
                ('amount_payable', models.IntegerField()),
                ('current_reading', models.IntegerField()),
                ('previous_reading', models.IntegerField()),
                ('current_data', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=35)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TipsAndAdvertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tip_advertising', models.CharField(max_length=20)),
                ('type_data', models.CharField(choices=[('tip', 'Tip'), ('adv', 'Advertising')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='municipality',
            name='key_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.State'),
        ),
        migrations.AddField(
            model_name='contract',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Municipality'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Rate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='receipt',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Receipt'),
        ),
        migrations.AddField(
            model_name='contract',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.State'),
        ),
    ]
