# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_mun', models.IntegerField()),
                ('name_mun', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ('key_state__key_state',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_state', models.IntegerField()),
                ('state', models.CharField(max_length=35)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('key_state',),
            },
        ),
        migrations.AddField(
            model_name='municipality',
            name='key_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.State'),
        ),
    ]
