# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AlterField(
            model_name='municipality',
            name='key_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.State'),
        ),
        migrations.AlterField(
            model_name='state',
            name='key_state',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
