# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_contract', models.IntegerField()),
                ('rate', models.CharField(choices=[('tarifa1', 'TARIFA 1'), ('tarifa1A', 'TARIFA 1A')], max_length=10)),
                ('period', models.CharField(max_length=20)),
                ('type_payment', models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral')], max_length=20)),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Municipality')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.State')),
            ],
        ),
    ]
