# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 17:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=30)),
                ('kilowatt', models.CharField(max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
            ],
            options={
                'verbose_name_plural': 'Historial',
                'verbose_name': 'Historial',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='LimitRateDac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rate', models.CharField(choices=[('TARIFA 1', 'TARIFA 1'), ('TARIFA 1A', 'TARIFA 1A'), ('TARIFA 1B', 'TARIFA 1B'), ('TARIFA 1C', 'TARIFA 1C'), ('TARIFA 1D', 'TARIFA 1D'), ('TARIFA 1E', 'TARIFA 1E'), ('TARIFA 1F', 'TARIFA 1F')], max_length=30)),
                ('kilowatt', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Limite DAC',
                'verbose_name': 'Limite DAC',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('premium', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Perfile',
            },
        ),
        migrations.CreateModel(
            name='RateHighComsuption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('fixed_charge', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('cost_verano', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('cost_no_verano', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('unique_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
            ],
            options={
                'verbose_name_plural': 'Tarifa Alto Consumo',
                'verbose_name': 'Tarifa Alto Consumo',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('day', models.CharField(max_length=10)),
                ('daily_reading', models.IntegerField(default=0)),
                ('hours_elapsed', models.CharField(max_length=10)),
                ('hours_totals', models.CharField(max_length=10)),
                ('days_elapsed', models.CharField(max_length=10)),
                ('days_totals', models.CharField(max_length=10)),
                ('daily_consumption', models.CharField(max_length=10)),
                ('cumulative_consumption', models.CharField(max_length=10)),
                ('average_global', models.CharField(max_length=10)),
                ('rest_day', models.CharField(blank=True, max_length=10, null=True)),
                ('projection', models.CharField(max_length=25)),
                ('projected_payment', models.CharField(max_length=30)),
                ('amount_payable', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Record',
                'ordering': ('-date', '-daily_reading'),
            },
        ),
        migrations.CreateModel(
            name='TableRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Regiones',
                'verbose_name': 'Regiones',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('id',), 'verbose_name': 'Contrato'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('name_mun',), 'verbose_name': 'Municipio'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('id',), 'verbose_name': 'Tarifa'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ('id',), 'verbose_name': 'Recibo'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('id',), 'verbose_name': 'Estado'},
        ),
        migrations.AlterModelOptions(
            name='tipsandadvertising',
            options={'ordering': ('id',), 'verbose_name': 'Tip'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='period_summer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='key_state',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='current_data',
        ),
        migrations.AddField(
            model_name='contract',
            name='finalDateRange',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='initialDateRange',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='apps.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='apps.Contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='current_reading_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='period',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number_contract',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rate',
            field=models.CharField(choices=[('TARIFA 1', 'TARIFA 1'), ('TARIFA 1A', 'TARIFA 1A'), ('TARIFA 1B', 'TARIFA 1B'), ('TARIFA 1C', 'TARIFA 1C'), ('TARIFA 1D', 'TARIFA 1D'), ('TARIFA 1E', 'TARIFA 1E'), ('TARIFA 1F', 'TARIFA 1F')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='type_payment',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Bimestral', 'Bimestral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='rate',
            field=models.CharField(choices=[('TARIFA 1', 'TARIFA 1'), ('TARIFA 1A', 'TARIFA 1A'), ('TARIFA 1B', 'TARIFA 1B'), ('TARIFA 1C', 'TARIFA 1C'), ('TARIFA 1D', 'TARIFA 1D'), ('TARIFA 1E', 'TARIFA 1E'), ('TARIFA 1F', 'TARIFA 1F')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='consumption_name',
            field=models.CharField(choices=[('Consumo Basico', 'Consumo Básico'), ('Consumo Intermedio', 'Consumo Intermedio'), ('Consumo Intermedio Alto', 'Consumo Intermedio Alto'), ('Consumo Excedente', 'Consumo Excedente')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rate',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='kilowatt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='name_rate',
            field=models.CharField(choices=[('TARIFA 1', 'TARIFA 1'), ('TARIFA 1A', 'TARIFA 1A'), ('TARIFA 1B', 'TARIFA 1B'), ('TARIFA 1C', 'TARIFA 1C'), ('TARIFA 1D', 'TARIFA 1D'), ('TARIFA 1E', 'TARIFA 1E'), ('TARIFA 1F', 'TARIFA 1F')], max_length=15),
        ),
        migrations.AlterField(
            model_name='rate',
            name='period_name',
            field=models.CharField(choices=[('Verano', 'Verano'), ('NoVerano', 'Fuera de Verano')], max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount_payable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='current_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipsandadvertising',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='records',
            name='contracts',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Contract'),
        ),
        migrations.AddField(
            model_name='ratehighcomsuption',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_hight', to='apps.TableRegion'),
        ),
        migrations.AddField(
            model_name='history',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_history', to='apps.Contract'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region_mun', to='apps.TableRegion'),
            preserve_default=False,
        ),
    ]
