# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payday_limit', models.DateField()),
                ('amount_payable', models.IntegerField()),
                ('current_reading', models.IntegerField()),
                ('previous_reading', models.IntegerField()),
                ('current_data', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='name_contract',
            field=models.CharField(default='casa', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Municipality'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='period',
            field=models.CharField(choices=[('ene_jun', 'Enero - Junio'), ('jun_dic', 'Junio - Diciembre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.State'),
        ),
        migrations.AddField(
            model_name='contract',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Receipt'),
        ),
    ]
