# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 16:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20171111_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateHighConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('fixed_charge', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('cost_verano', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('cost_no_verano', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_hight', to='apps.TableRegion')),
            ],
            options={
                'verbose_name_plural': 'Tarifa Alto Consumo',
                'ordering': ('id',),
                'verbose_name': 'Tarifa Alto Consumo',
            },
        ),
        migrations.RemoveField(
            model_name='ratehighcomsuption',
            name='region',
        ),
        migrations.AddField(
            model_name='contract',
            name='high_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RateHighComsuption',
        ),
    ]
