# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20170904_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
