# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20170717_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='cost',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
