# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20170712_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsAndAdvertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tip_advertising', models.CharField(max_length=20)),
                ('type_data', models.CharField(choices=[('tip', 'Tip'), ('adv', 'Advertising')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='period',
            new_name='period_summer',
        ),
        migrations.AlterField(
            model_name='contract',
            name='rate',
            field=models.CharField(choices=[('tarifa1', 'TARIFA 1'), ('tarifa1a', 'TARIFA 1A'), ('tarifa1b', 'TARIFA 1B'), ('tarifa1c', 'TARIFA 1C'), ('tarifa1d', 'TARIFA 1D'), ('tarifa1e', 'TARIFA 1E'), ('tarifa1f', 'TARIFA 1F')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='receipt',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.Receipt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.State'),
        ),
    ]
