# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_profile_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('daily_reading', models.IntegerField(default=0)),
                ('hours_elapsed', models.CharField(max_length=10)),
                ('hours_totals', models.CharField(max_length=10)),
                ('days_elapsed', models.CharField(max_length=10)),
                ('days_totals', models.CharField(max_length=10)),
                ('daily_consumption', models.IntegerField(default=0)),
                ('cumulative_consumption', models.CharField(max_length=10)),
                ('actual_consumption', models.CharField(max_length=10)),
                ('average_global', models.CharField(max_length=10)),
                ('rest_day', models.CharField(blank=True, max_length=10, null=True)),
                ('projection', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'date',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='records',
            field=models.ManyToManyField(blank=True, to='apps.Records'),
        ),
    ]
