# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20171114_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
