# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20171113_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='high_consumption',
            field=models.BooleanField(default=False),
        ),
    ]
