# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20170717_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='cost',
            field=models.FloatField(default=None),
        ),
    ]
