# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20170904_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number_contract',
            field=models.CharField(max_length=15),
        ),
    ]
