# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20170905_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='current_reading',
            field=models.IntegerField(default=0),
        ),
    ]
