# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 23:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20170717_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='kilowatt',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
