# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20171123_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_purchase',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
