# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20170905_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amount_payable',
            field=models.IntegerField(default=0),
        ),
    ]
