# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20171009_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'Record'},
        ),
    ]
