# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20170905_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='period',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
