# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20171009_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='records',
        ),
        migrations.AddField(
            model_name='records',
            name='contracts',
            field=models.ManyToManyField(blank=True, to='apps.Contract'),
        ),
    ]
