# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20171009_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='current_reading_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
