# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20170718_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='kilowatt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
