# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20171009_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='contracts',
        ),
        migrations.AddField(
            model_name='records',
            name='contracts',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.Contract'),
            preserve_default=False,
        ),
    ]
