# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20171010_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='daily_consumption',
            field=models.CharField(max_length=10),
        ),
    ]
