# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20171011_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='actual_consumption',
        ),
        migrations.AddField(
            model_name='records',
            name='projected_payment',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
