# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20170718_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='rate',
            field=models.CharField(choices=[('TARIFA 1', 'TARIFA 1'), ('TARIFA 1A', 'TARIFA 1A'), ('TARIFA 1B', 'TARIFA 1B'), ('TARIFA 1C', 'TARIFA 1C'), ('TARIFA 1D', 'TARIFA 1D'), ('TARIFA 1E', 'TARIFA 1E'), ('TARIFA 1F', 'TARIFA 1F')], max_length=30),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='rate',
            field=models.CharField(choices=[('TARIFA 1', 'TARIFA 1'), ('TARIFA 1A', 'TARIFA 1A'), ('TARIFA 1B', 'TARIFA 1B'), ('TARIFA 1C', 'TARIFA 1C'), ('TARIFA 1D', 'TARIFA 1D'), ('TARIFA 1E', 'TARIFA 1E'), ('TARIFA 1F', 'TARIFA 1F')], max_length=20),
        ),
    ]
