# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_auto_20170718_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='period_summer',
            field=models.CharField(choices=[('Verano', 'Febrero - Julio'), ('Verano', 'Marzo - Agosto'), ('Verano', 'Abril - Septiembre'), ('Verano', 'Mayo - Octubre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rate',
            field=models.CharField(choices=[('TARIFA 1', 'TARIFA 1'), ('TARIFA 1A', 'TARIFA 1A'), ('TARIFA 1B', 'TARIFA 1B'), ('TARIFA 1C', 'TARIFA 1C'), ('TARIFA 1D', 'TARIFA 1D'), ('TARIFA 1E', 'TARIFA 1E'), ('TARIFA 1F', 'TARIFA 1F')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='type_payment',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Bimestral', 'Bimestral')], max_length=20),
        ),
    ]
