# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20170718_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='rate',
        ),
        migrations.AlterField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.State'),
            preserve_default=False,
        ),
    ]
