# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20170718_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='current_data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
