# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20171017_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
