# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20170718_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contrato'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('state',), 'verbose_name': 'Municipio'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Tarifa'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Recibo'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('id',), 'verbose_name': 'Estado'},
        ),
        migrations.AlterModelOptions(
            name='tipsandadvertising',
            options={'verbose_name': 'Tip'},
        ),
        migrations.AlterField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='apps.State'),
        ),
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together=set([('state',)]),
        ),
    ]
