# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_auto_20171017_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='contracts',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.Contract'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
