# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 14:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20171017_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=30)),
                ('kilowatt', models.CharField(max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.001)])),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Historial',
            },
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'ordering': ('-date', '-daily_reading'), 'verbose_name': 'Record'},
        ),
        migrations.AlterModelOptions(
            name='tipsandadvertising',
            options={'ordering': ('id',), 'verbose_name': 'Tip'},
        ),
    ]
