# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_auto_20171023_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
