# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20170725_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='apps.State'),
        ),
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together=set([('state',)]),
        ),
    ]
