# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_history_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='status',
        ),
        migrations.AddField(
            model_name='records',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
