# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20171024_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
