# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_auto_20171024_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='day',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
