# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_auto_20170725_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('name_mun',), 'verbose_name': 'Municipio'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('id',), 'verbose_name': 'Tarifa'},
        ),
    ]
