# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_auto_20170727_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Receipt'),
        ),
    ]
