# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_auto_20171024_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='amount_payable',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
