# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_records_amount_payable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('id',), 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
        migrations.AddField(
            model_name='history',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contract_history', to='apps.Contract'),
            preserve_default=False,
        ),
    ]
