# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_auto_20170801_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='period_summer',
            field=models.CharField(blank=True, choices=[('Verano', 'Febrero - Julio'), ('Verano', 'Marzo - Agosto'), ('Verano', 'Abril - Septiembre'), ('Verano', 'Mayo - Octubre')], max_length=20, null=True),
        ),
    ]
