# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_auto_20170802_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='current_data',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='current_reading',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='previous_reading',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
