# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_auto_20170802_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='current_data',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='current_reading',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='previous_reading',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
