# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_auto_20170802_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='current_data',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='current_reading',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='previous_reading',
            field=models.IntegerField(),
        ),
    ]
