# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_auto_20170802_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='receipt',
        ),
        migrations.AddField(
            model_name='contract',
            name='receipt',
            field=models.ManyToManyField(blank=True, null=True, to='apps.Receipt'),
        ),
    ]
