# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_auto_20170803_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
