# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_contract_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
