# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_auto_20170804_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipsandadvertising',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
