# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0033_auto_20170804_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('id',), 'verbose_name': 'Contrato'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ('id',), 'verbose_name': 'Recibo'},
        ),
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
