# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_auto_20170814_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
