# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='rate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apps.Rate'),
            preserve_default=False,
        ),
    ]
