# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_auto_20170815_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='finalDateRange',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='initialDateRange',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='current_data',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
