# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0043_auto_20170829_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='period_summer',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
