# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0044_auto_20170904_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
